### ISSUE TITLE
公众号历史文章抓取问题

### ISSUE THREAD

**Issue by MarloweW** [bowenpay/wechat-spider#14]
本项目想在的框架下面，似乎没有手段能方便的取到一个公帐号的历史文章数据？只能限制在最近 10 条？

**Comment by yijingping** [comment]
是的，没有办法。
因为文章是从搜狗微信爬取过来的，微信号下面只展示最近群发的10条。 
最初这个功能我是写了的，搜狗微信改版后去掉了。

**Comment by MarloweW** [comment]
好吧，那这个功能我只能另想办法了。
