### ISSUE TITLE
后台 add  报错

### ISSUE THREAD

**Issue by guotie** [bowenpay/wechat-spider#2]
ServerError at /wechat/add/
{'status': 400, 'details': {}}
Request Method:	POST
Request URL:	http://xxxx/wechat/add/
Django Version:	1.8.1
Exception Type:	ServerError
Exception Value:	
{'status': 400, 'details': {}}
Exception Location:	/usr/local/lib/python2.7/dist-packages/oss2/api.py in _do, line 149
Python Executable:	/usr/bin/python
Python Version:	2.7.9
Python Path:	
['/root/wechat-spider',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	星期三, 21 九月 2016 21:51:40 +0800

**Comment by guotie** [comment]
好像是 oss 没有配置，必须使用oss 吗？

**Comment by yijingping** [comment]
不是必须的，可以不存储图片，爬取速度更快。 你确定有问题吗？我检查一下代码

**Comment by guotie** [comment]
我自己改成保存为文件了
