### ISSUE TITLE
可以保存图片吗？

### ISSUE THREAD

**Issue by haodong** [bowenpay/wechat-spider#32]
有的文章过阵子就被删了 要是能有一个保存图片到本地服务器/云的功能就好了

**Comment by yijingping** [comment]
有。可以使用阿里云OSS保存图片。 参照 Readme中 `local_settings.py` 配置说明去做就行。

**Comment by haodong** [comment]
成功了 感谢！

**Comment by haodong** [comment]
设置完成，我发现文章标签的图片已经在OSS里
但是文章内容里的贴图仍然是 mmbiz.qpic.cn
请问这个问题可以解决吗？

**Comment by yijingping** [comment]
已经加上了这个功能了。 请pull 最新的代码。 效果如下：

![image](https://cloud.githubusercontent.com/assets/2122123/21087158/2d0f67be-c05e-11e6-97fb-5c78e533d187.png)

**Comment by haodong** [comment]
谢谢 可以了
