### ISSUE TITLE
为什么我安装不成功啊  帮我看看

### ISSUE THREAD

**Issue by hide9527** [bowenpay/wechat-spider#35]
File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 27, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: libmysqlclient_r.so.16: cannot open shared object file: No such file or directory

类似这样的 是什么原因呢

**Comment by yijingping** [comment]
应该是没有安装mysql依赖库 你搜mysql-python 安装
