### ISSUE TITLE
在windows7下安装所有库后，咋初始化数据表啊？

### ISSUE THREAD

**Issue by liwan123123** [bowenpay/wechat-spider#37]
5) 更新配置文件local_settings 这步也完成了，到第六步咋初始化数据表啊？$ python manage.py migrate这个是在linux下的，在windows下咋弄呢？

另外python manage.py runserver 0.0.0.0:8001这个命令在windows下不能用吧？不知道您这个程序能否在windows7下运行？？？

**Comment by liwan123123** [comment]
另外还有supervisor这样的在windows下咋实现呢？？

**Comment by yijingping** [comment]
目前没有在windows下 测试过。  应该要做些改动才能跑。你如果感兴趣，可以给我提交pull request。 加我微信，我告诉你大致需要改哪些地方

**Comment by liwan123123** [comment]
大神你微信多少啊？我的是liwan6789
