### ISSUE TITLE
启动爬虫后无法下载

### ISSUE THREAD

**Issue by wjwish** [bowenpay/wechat-spider#38]
启动爬虫步骤中，“extractor”和“processor”输入后终端没有反应，浏览器“等待下载“数量有增加，但”最新文章“无更新，请问是什么原因？

**Comment by yijingping** [comment]
看看downloader中有什么报错？ 发出来看下

**Comment by wjwish** [comment]
downloader没有报错，可以正常运行。只是“extractor”和“processor”运行一段时间后自动停止。
今天只有“processor”会运行大约半小时就停止。

**Comment by yijingping** [comment]
我也会遇到这种情况，所以用supervisor监控，如果停止就重新启动。  
我后面去看看错误日志，把这些问题修复掉
