### ISSUE TITLE
我想知道这个东西有个屌用啊

### ISSUE THREAD

**Issue by ShangXinbo** [bowenpay/wechat-spider#4]

**Comment by BenBBear** [comment]
建议把用词改一下， 比如 `自己不太明白， 想问一下这个应用的具体用户，应用场景和需求。`  大老爷们儿说话要有规矩。

**Comment by yijingping** [comment]
@ShangXinbo 
1 我写这个爬虫，主要是用来采集最新的公益项目信息，以及 受助者信息。以最快的速度帮他们对接。

2 其它的应用，可以看看：[新榜-内容创业服务](http://www.newrank.cn/) 、[传播易-微信广告投放（已在新三板上市）](http://www.chuanboyi.com/) 、 还有一些用来追踪热点炒股、大数据分析企业营销效果、企业舆情监测的。

3 做这个东西，并没有一开始就设想很多应用场景，只是先解决我自己的问题。

@BenBBear  说的对。要做一个耐撕的人。
