### ISSUE TITLE
添加公众号后文章无法获取

### ISSUE THREAD

**Issue by leipu247** [bowenpay/wechat-spider#48]
# 添加公众号后文章无法获取
 我使用的是os系统，根据提示完成安装后 添加了公众号 ,可是公众号内的文章无法获取(公众号内已发表文章)
![bc883c44-9d7c-4903-a2a4-57077d805a9b](https://cloud.githubusercontent.com/assets/24392167/25164488/d341d856-2503-11e7-801d-14c01c93429f.png)

 请看看这是什么原因呢

**Comment by yijingping** [comment]
你主要看这4个脚本是否运行正常，是否打印了什么异常日志：
```
$ python bin/scheduler.py
$ python bin/downloader.py
$ python bin/extractor.py
$ python bin/processor.py
```

**Comment by LittlePisum** [comment]
收到 谢谢
