### ISSUE TITLE
发现一个关于redis消息队列的bug．

### ISSUE THREAD

**Issue by hiber-niu** [bowenpay/wechat-spider#55]
@yijingping 在参考的配置文件中是先启动scheduler，然后启动downloader，所以在用supervisord启动时，测试时会有首次启动时的启动任务丢失，downloader需要下次启动才会正常运行．
将downloader先于scheduler启动会避免这个问题．

**Comment by yijingping** [comment]
把local_settings.py 中的 CRAWLER_DEBUG = True 改为 False，或者删掉就行。 这是为了测试用的。

![image](https://cloud.githubusercontent.com/assets/2122123/26517688/c9354a42-42d0-11e7-825f-a4563fdf7071.png)
