### ISSUE TITLE
请问您这个项目拿到投资了么？

### ISSUE THREAD

**Issue by dennis88888** [bowenpay/wechat-spider#62]
RT

**Comment by yijingping** [comment]
有投资

**Comment by dennis88888** [comment]
自我介绍下，我之前供职于IBM，苏宁等，现在在某央企做架构师
大大去年说过2020年实现全面脱贫，那您的项目如何保持可持续发展性？

**Comment by yijingping** [comment]
在官网 http://0fenbei.com/ 有盈利方式的简单说明。 如果感兴趣可以加我微信 jingpingyi 私聊。
